apiVersion: v1
kind: PersistentVolume
metadata:
  name: databasevolume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: datastorage
  hostPath:
    path: ./db