
name: full-stack

services:

  frontend:
    build: 
      context: ./angular_frontend
    container_name: my-frontend
    ports:
      - '80:80'
    
  backend:
    build:
      context: ./angular_class_nest
    # container_name: my-backend
    
    ports:
      - '8082:8082'  
    environment:
      DB_PORT: 5432
      DB_HOST: db
      DB_USERNAME: angular_postgress
      DB_PASSWORD: AngularClass
      DB_NAME: ang_postgres
    depends_on:
      - db
      - frontend
    networks:
      - afc
    restart: always

  db:
    image: postgres:13.16-bookworm
    # container_name: database
    environment:
      POSTGRES_USER: angular_postgress
      POSTGRES_PASSWORD: AngularClass
      POSTGRES_DB: ang_postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - afc

volumes:
   db_data:

networks:
  afc:
    driver: bridge

