apiVersion: v1
kind: Pod
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend
spec:
  containers:
  - name: angular-frontend
    image: ariwesi/angular-front:latest
    ports:
    - containerPort: 80
