apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      tolerations:
      - key: "key1"
        operator: "Equal"
        value: "value1"
      #nodeName: minikube-m03
      #nodeSelector:
       # team: dev
      containers:
      - name: angular-frontend
        image: ariwesi/angular-front:latest
        ports:
        - containerPort: 80
